apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: joouvobme-python 
  janus-idp.io/tekton: joouvobme-python
  backstage.io/kubernetes-id: joouvobme-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: joouvobme-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  